language: scala

scala:
  - 2.13.1
  - 2.12.10

jdk: openjdk8

dist: trusty
sudo: required

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache
    - '.hoarder-cache'

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "DryhI4ljTOwUlitQRbMjelgsz1DFU0c9AhevIX3zeLjCaaCwcjw9VHCIj9W0GvxRZIqIiGNmegJL1FaHssivnEy2NBGwcn3uYMmrPu+1svYLx42Hd74k0KNkvgZBAkb5+/U0FPn1u3BXzHkfRgYY2K8cmQFoHdbCj+iB6tl6r9mLxGbjfmz0cGG1TF5PSiJWQv4XcAlVqzgAzOvIYQVy9ZylYWoy73AddzedQVbt6CsTy5DpWZU/SOUmyUqEA4g9t57JTa/pPk6dL3ER4IzJmijEzWkWA+IJCgeXhtjlQAh/4ONYQKXwvt2DSL1VdhGp/wM/lVsf9SwK9E0fdfDS/A5/c/jrIISCbBtFlMwog433DpFYqGRyTVT4+FgPU2UKH6wwDuyFfYKAnDPeLtBZUmcYaEY7JCJUaenY/38gTpChsunv2q15/uu48WzDWu9U9H76I5EkxHV7+NUx7raSAu2guGei7aiYmXnRYSguxvkIvX2SD5SSV92XMq95bcflDRrnkF+inGXqYT3yrG3M9SMLohpXo6XBUh7qjtWELi7sSCPbqGPzPwiDdd2IX+r0CvAiRHfi6PMUcL10Eg3DDqEXEyPgprWwfuROzi31T1ukIoA9sYALCiKP4xTUdTh+z1Z9/T6X648fG84k+Tf/zgZTVQ7ASuA9edcFvAAnaUY="
    # GITHUB_TOKEN
    - secure: "fA9M5r5UYaNVCVigaYiqONbB+W94+9hieGMwLH36ER2ya+ZfLvbMNcDoWYRMSE8PP7yA1X/yqRYgAWE1PqkQsGfNagyqaOzyJLU1YfvLXawDeZWLnJ3oUUuqGs1S3GlRn/L7le80cPEQrear6PIzYDXYkwuFi5tB4XMk2bKxZXSFXXeWnqSDUQ3GoMbODY7ebWNzFEwWL3471RaQAwyJIleR4RPJbg9btpzS0AH7VAHBjUxsjdsWAtUEE44RXGvyisgPcX4wqtAIys80YtqOKykYqyi1A6x1WmTEj3sZp+p1wIeYLqvlPADR9ElSO7JI8InUiMElvF7B03z7aRvYiODa91bMfRwbLuehkAN/mIdEquRDBGCRJTMqxFQRlSd4tJQ5bcC+Hp/9MNzAheTBQSbajXZnH9QWwyFHG6+WdXCvlayn55OzNFnEQ24UqPwZQ6YlOU93mzAROvQTkdTu3/CEPnNkj1l6uF5v/C0bU/wuAzt8CUDFfnLsx/3eRTWn6bDcDULgfGiQcH0h143A/brhPycD46+oPhUdZC+K8fIlsUTGUgBwQsjCfNVe9xb4ElNpUybH2JEMlkf0Z5778Al0rLoCcVEQ8qLRs2Hcs1hR14eA9Nc6pXv2ZZWeshONqPxqq3Sa7hKO74+xzAOYJKY/fu5qFpY/zdpTNBid2Vo="
    # GITHUB_ACCESS_TOKEN
    - secure: "yjkz9di2fEq9L2cA/7jWZKFxoKWNpg2RL/EQwo/wU+9dR1ua8YPt4mppwIPfHZkVEHpvZEHhy+j88ZcgamOHPWg42qrHq2yPwxEjSqNv399HaNW9+iHwsawxUwnhAXsTH7LNELi8lXc2E749zziqIQhAS42sXcMdgRyzhyKNn/Fn88/qy4n/mDSsBqhBOiwGBdkbpa4koBfXQxsYr5DeMmuK5ZtbZXWdvjkY3DSk2M+aIUezNw4ejD2KkIq9bUdSRX40N4R1h4eS3G0AHTz9NQGYcDHbJzpeo1TE9Fnev00nmwjZJlWjP4mTf+DfMj4kBjVyYy2gHBNNsyZdaeoYHPsEABNZ/+JnY9VDAY16961VAm5W0zxd/yb05W91qccaE6q8zNDomp3kkdDu1LKGF9RHRVb0gn0ZZSmJULAwBUjd3qTJn79SYyAanP+bYDg+5Nn+1ns2104dD2F/ftGdKdMloyMXiwUsf6jHvulyMENzWL/WAB0StGhXZhUDkV8PwC7LbGxAUngr1MeXr6ac/iVfadoF8btRMHcIK09c6k9QrxdJhrg08nyxqxIUNp66zZeUZ8Og9XyngY74I1vbtlV/+1yHiXBrexXcphnRKJuhpFn4ancTRYJTZfNZYIdV+R6Ylq6IJ7P51HJAPpWFIHCIKYHARolr2WiqnC8olT8="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "0xUWVdSEIVTOXJuToo4BTrZhqrgc3jVuRvTufIkR/gKbMxxx9H5m+23WdPYHNRlxPO/z+6Himy6WQv27cERk8wS2qwuIesMZ9fiyA+dUYS/sjxnSNSp3GGz4qLQaeggkSd6meznWQNC7216u7WJZ6xyp7C7TWaHfpWyrLIDxue8MUhE5904nAQpUJGCRfRKdoy4zfS8YUkEh4ja7wIRLyLEP6Wv3twa0g7ExHBnw5Melj3uQIl/J4M71XMH+jHlHvac4KWNnh9Pfph44Hpq1n8Vmy6iNoRx2Y5YWxfe6gXFVRSDG+Xg2cZ3HJ/8qimobF+9vjwSq8vugVpqM7cA6Ikk+y94k+6cGPBkvK6/FTqOQUbsYNG0tmGgnWCO47/5Ue6QtB9Ygx5IersJCPtYhMLuGk9e9j37Gms3+W1uwEm2QnJ577zzrxgGg5+VCjY5BtMjK3NZ2q8rLy8VB7gXjkIz32QvBfU8ejyjv15BnD3TFBn/eY5oiiEHARR8F/XTDc8+kMpYK+UFA1p47kc2dIAuESS4ZNpGvCJMgEdn3fo3WQP2zt3BiDLtaFEByr26PLe4CaktSoJWRsXXwbiFD/0HoYUbEw04NXpMEVhpyCnj9BIGe+EtjLzF0/opgafiDBbGXhmaYQ6dsQ8iIocuELb6Z6mLgsFzHNKGhOSlu1wI="

install:
  - $SBT transferCommonResources
  - scripts/commonSetup

script:
  - set -e
  - $SBT ++$TRAVIS_SCALA_VERSION test

  - |-
    if [[ "$TRAVIS_SCALA_VERSION" =~ 2.12 ]]; then
      if [ $TRAVIS_PULL_REQUEST == "false" ] && [[ "$TRAVIS_BRANCH" =~ backport/v.*|master ]]; then
        TRAVIS_JOB_NUMBER=1 scripts/qdataPublishAndTag
      fi

      scripts/checkAndAutoMerge
    fi

after_success:
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/
