#!/usr/bin/env bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

"$SBT" transferPublishAndTagResources

scripts/publishAndTag 'slamdata/qdata'

bumpInDownstream() { echo $1 > qdata-version; }
export -f bumpInDownstream

for c in quasar quasar-repl mimir slamdata-backend scion; do
  scripts/bumpDependentProject slamdata $c bumpInDownstream
done
